# Site settings
title: Кодерские байки
email: poetinthecode@gmail.com
description: | # this means to ignore newlines until "baseurl:"
  «Большинство хороших программистов делают свою работу не потому, что ожидают оплаты или признания, а потому что получают удовольствие от программирования.» Л.Торвальдс
baseurl: "" # the subpath of your site, e.g. /blog/
url: "poetofcode.com" # the base hostname & protocol for your site
twitter_username: poetofcode
github_username:  poetofcode

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 10
exclude: [_excluded, start_server.bat, tmpls_go, config_go.json, new_post.exe]
gems: [jekyll-paginate]
theme: jekyll-theme-cayman