# Site settings
title: poetofcode.ru
email: poetinthecode@gmail.com
description: | # this means to ignore newlines until "baseurl:"
  «Большинство хороших программистов делают свою работу не потому, что ожидают оплаты или признания, а потому что получают удовольствие от программирования.» Л.Торвальдс
baseurl: "" # the subpath of your site, e.g. /blog/
excerpt_separator: <!--more-->
url: "poetofcode.ru" # the base hostname & protocol for your site
twitter_username: poetofcode
github_username:  poetofcode
author: poetofcode
logo: /images/blog_icon.png
lang: ru_RU
social:
  name: poetofcode
  links:
    - https://twitter.com/poetofcode
    - https://github.com/poetofcode
    - https://bitbucket.org/poetofcode
twitter:
  username: poetofcode
  card: summary

# Front matter defaults
defaults:
  - scope:
      path: ""  # an empty string here means all files in the project, details: https://jekyllrb.com/docs/configuration/#front-matter-defaults
    values:
      image: /images/blog_icon.png

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 10
exclude: [_excluded, start_server.bat, tmpls_go, config_go.json, new_post.exe]
gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]